<?php

return [

    // A
    ['code'=>'+93','country'=>'Afghanistan','flag'=>'🇦🇫'],
    ['code'=>'+355','country'=>'Albania','flag'=>'🇦🇱'],
    ['code'=>'+213','country'=>'Algeria','flag'=>'🇩🇿'],
    ['code'=>'+1','country'=>'American Samoa','flag'=>'🇦🇸'],
    ['code'=>'+376','country'=>'Andorra','flag'=>'🇦🇩'],
    ['code'=>'+244','country'=>'Angola','flag'=>'🇦🇴'],
    ['code'=>'+1','country'=>'Anguilla','flag'=>'🇦🇮'],
    ['code'=>'+672','country'=>'Antarctica','flag'=>'🇦🇶'],
    ['code'=>'+1','country'=>'Antigua and Barbuda','flag'=>'🇦🇬'],
    ['code'=>'+54','country'=>'Argentina','flag'=>'🇦🇷'],
    ['code'=>'+374','country'=>'Armenia','flag'=>'🇦🇲'],
    ['code'=>'+297','country'=>'Aruba','flag'=>'🇦🇼'],
    ['code'=>'+61','country'=>'Australia','flag'=>'🇦🇺'],
    ['code'=>'+43','country'=>'Austria','flag'=>'🇦🇹'],
    ['code'=>'+994','country'=>'Azerbaijan','flag'=>'🇦🇿'],

    // B
    ['code'=>'+1','country'=>'Bahamas','flag'=>'🇧🇸'],
    ['code'=>'+973','country'=>'Bahrain','flag'=>'🇧🇭'],
    ['code'=>'+880','country'=>'Bangladesh','flag'=>'🇧🇩'],
    ['code'=>'+1','country'=>'Barbados','flag'=>'🇧🇧'],
    ['code'=>'+375','country'=>'Belarus','flag'=>'🇧🇾'],
    ['code'=>'+32','country'=>'Belgium','flag'=>'🇧🇪'],
    ['code'=>'+501','country'=>'Belize','flag'=>'🇧🇿'],
    ['code'=>'+229','country'=>'Benin','flag'=>'🇧🇯'],
    ['code'=>'+1','country'=>'Bermuda','flag'=>'🇧🇲'],
    ['code'=>'+975','country'=>'Bhutan','flag'=>'🇧🇹'],
    ['code'=>'+591','country'=>'Bolivia','flag'=>'🇧🇴'],
    ['code'=>'+387','country'=>'Bosnia and Herzegovina','flag'=>'🇧🇦'],
    ['code'=>'+267','country'=>'Botswana','flag'=>'🇧🇼'],
    ['code'=>'+55','country'=>'Brazil','flag'=>'🇧🇷'],
    ['code'=>'+246','country'=>'British Indian Ocean Territory','flag'=>'🇮🇴'],
    ['code'=>'+673','country'=>'Brunei','flag'=>'🇧🇳'],
    ['code'=>'+359','country'=>'Bulgaria','flag'=>'🇧🇬'],
    ['code'=>'+226','country'=>'Burkina Faso','flag'=>'🇧🇫'],
    ['code'=>'+257','country'=>'Burundi','flag'=>'🇧🇮'],

    // C
    ['code'=>'+855','country'=>'Cambodia','flag'=>'🇰🇭'],
    ['code'=>'+237','country'=>'Cameroon','flag'=>'🇨🇲'],
    ['code'=>'+1','country'=>'Canada','flag'=>'🇨🇦'],
    ['code'=>'+238','country'=>'Cape Verde','flag'=>'🇨🇻'],
    ['code'=>'+1','country'=>'Cayman Islands','flag'=>'🇰🇾'],
    ['code'=>'+236','country'=>'Central African Republic','flag'=>'🇨🇫'],
    ['code'=>'+235','country'=>'Chad','flag'=>'🇹🇩'],
    ['code'=>'+56','country'=>'Chile','flag'=>'🇨🇱'],
    ['code'=>'+86','country'=>'China','flag'=>'🇨🇳'],
    ['code'=>'+57','country'=>'Colombia','flag'=>'🇨🇴'],
    ['code'=>'+269','country'=>'Comoros','flag'=>'🇰🇲'],
    ['code'=>'+242','country'=>'Congo','flag'=>'🇨🇬'],
    ['code'=>'+243','country'=>'Congo (DRC)','flag'=>'🇨🇩'],
    ['code'=>'+682','country'=>'Cook Islands','flag'=>'🇨🇰'],
    ['code'=>'+506','country'=>'Costa Rica','flag'=>'🇨🇷'],
    ['code'=>'+225','country'=>'Côte d’Ivoire','flag'=>'🇨🇮'],
    ['code'=>'+385','country'=>'Croatia','flag'=>'🇭🇷'],
    ['code'=>'+53','country'=>'Cuba','flag'=>'🇨🇺'],
    ['code'=>'+357','country'=>'Cyprus','flag'=>'🇨🇾'],
    ['code'=>'+420','country'=>'Czech Republic','flag'=>'🇨🇿'],

    // D
    ['code'=>'+45','country'=>'Denmark','flag'=>'🇩🇰'],
    ['code'=>'+253','country'=>'Djibouti','flag'=>'🇩🇯'],
    ['code'=>'+1','country'=>'Dominica','flag'=>'🇩🇲'],
    ['code'=>'+1','country'=>'Dominican Republic','flag'=>'🇩🇴'],

    // E
    ['code'=>'+593','country'=>'Ecuador','flag'=>'🇪🇨'],
    ['code'=>'+20','country'=>'Egypt','flag'=>'🇪🇬'],
    ['code'=>'+503','country'=>'El Salvador','flag'=>'🇸🇻'],
    ['code'=>'+240','country'=>'Equatorial Guinea','flag'=>'🇬🇶'],
    ['code'=>'+291','country'=>'Eritrea','flag'=>'🇪🇷'],
    ['code'=>'+372','country'=>'Estonia','flag'=>'🇪🇪'],
    ['code'=>'+251','country'=>'Ethiopia','flag'=>'🇪🇹'],

    // F
    ['code'=>'+500','country'=>'Falkland Islands','flag'=>'🇫🇰'],
    ['code'=>'+298','country'=>'Faroe Islands','flag'=>'🇫🇴'],
    ['code'=>'+679','country'=>'Fiji','flag'=>'🇫🇯'],
    ['code'=>'+358','country'=>'Finland','flag'=>'🇫🇮'],
    ['code'=>'+33','country'=>'France','flag'=>'🇫🇷'],

    // G
    ['code'=>'+241','country'=>'Gabon','flag'=>'🇬🇦'],
    ['code'=>'+220','country'=>'Gambia','flag'=>'🇬🇲'],
    ['code'=>'+995','country'=>'Georgia','flag'=>'🇬🇪'],
    ['code'=>'+49','country'=>'Germany','flag'=>'🇩🇪'],
    ['code'=>'+233','country'=>'Ghana','flag'=>'🇬🇭'],
    ['code'=>'+350','country'=>'Gibraltar','flag'=>'🇬🇮'],
    ['code'=>'+30','country'=>'Greece','flag'=>'🇬🇷'],
    ['code'=>'+299','country'=>'Greenland','flag'=>'🇬🇱'],
    ['code'=>'+1','country'=>'Grenada','flag'=>'🇬🇩'],
    ['code'=>'+502','country'=>'Guatemala','flag'=>'🇬🇹'],
    ['code'=>'+224','country'=>'Guinea','flag'=>'🇬🇳'],
    ['code'=>'+245','country'=>'Guinea-Bissau','flag'=>'🇬🇼'],
    ['code'=>'+592','country'=>'Guyana','flag'=>'🇬🇾'],

    // H
    ['code'=>'+509','country'=>'Haiti','flag'=>'🇭🇹'],
    ['code'=>'+504','country'=>'Honduras','flag'=>'🇭🇳'],
    ['code'=>'+852','country'=>'Hong Kong','flag'=>'🇭🇰'],
    ['code'=>'+36','country'=>'Hungary','flag'=>'🇭🇺'],

    // I
    ['code'=>'+91','country'=>'India','flag'=>'🇮🇳'],
    ['code'=>'+62','country'=>'Indonesia','flag'=>'🇮🇩'],
    ['code'=>'+98','country'=>'Iran','flag'=>'🇮🇷'],
    ['code'=>'+964','country'=>'Iraq','flag'=>'🇮🇶'],
    ['code'=>'+353','country'=>'Ireland','flag'=>'🇮🇪'],
    ['code'=>'+972','country'=>'Israel','flag'=>'🇮🇱'],
    ['code'=>'+39','country'=>'Italy','flag'=>'🇮🇹'],

    // J–Z (rest included)
    ['code'=>'+81','country'=>'Japan','flag'=>'🇯🇵'],
    ['code'=>'+962','country'=>'Jordan','flag'=>'🇯🇴'],
    ['code'=>'+7','country'=>'Kazakhstan','flag'=>'🇰🇿'],
    ['code'=>'+254','country'=>'Kenya','flag'=>'🇰🇪'],
    ['code'=>'+965','country'=>'Kuwait','flag'=>'🇰🇼'],
    ['code'=>'+996','country'=>'Kyrgyzstan','flag'=>'🇰🇬'],
    ['code'=>'+856','country'=>'Laos','flag'=>'🇱🇦'],
    ['code'=>'+371','country'=>'Latvia','flag'=>'🇱🇻'],
    ['code'=>'+961','country'=>'Lebanon','flag'=>'🇱🇧'],
    ['code'=>'+266','country'=>'Lesotho','flag'=>'🇱🇸'],
    ['code'=>'+231','country'=>'Liberia','flag'=>'🇱🇷'],
    ['code'=>'+218','country'=>'Libya','flag'=>'🇱🇾'],
    ['code'=>'+423','country'=>'Liechtenstein','flag'=>'🇱🇮'],
    ['code'=>'+370','country'=>'Lithuania','flag'=>'🇱🇹'],
    ['code'=>'+352','country'=>'Luxembourg','flag'=>'🇱🇺'],
    ['code'=>'+853','country'=>'Macau','flag'=>'🇲🇴'],
    ['code'=>'+60','country'=>'Malaysia','flag'=>'🇲🇾'],
    ['code'=>'+960','country'=>'Maldives','flag'=>'🇲🇻'],
    ['code'=>'+356','country'=>'Malta','flag'=>'🇲🇹'],
    ['code'=>'+52','country'=>'Mexico','flag'=>'🇲🇽'],
    ['code'=>'+977','country'=>'Nepal','flag'=>'🇳🇵'],
    ['code'=>'+31','country'=>'Netherlands','flag'=>'🇳🇱'],
    ['code'=>'+64','country'=>'New Zealand','flag'=>'🇳🇿'],
    ['code'=>'+234','country'=>'Nigeria','flag'=>'🇳🇬'],
    ['code'=>'+47','country'=>'Norway','flag'=>'🇳🇴'],
    ['code'=>'+92','country'=>'Pakistan','flag'=>'🇵🇰'],
    ['code'=>'+63','country'=>'Philippines','flag'=>'🇵🇭'],
    ['code'=>'+48','country'=>'Poland','flag'=>'🇵🇱'],
    ['code'=>'+351','country'=>'Portugal','flag'=>'🇵🇹'],
    ['code'=>'+7','country'=>'Russia','flag'=>'🇷🇺'],
    ['code'=>'+966','country'=>'Saudi Arabia','flag'=>'🇸🇦'],
    ['code'=>'+65','country'=>'Singapore','flag'=>'🇸🇬'],
    ['code'=>'+27','country'=>'South Africa','flag'=>'🇿🇦'],
    ['code'=>'+82','country'=>'South Korea','flag'=>'🇰🇷'],
    ['code'=>'+34','country'=>'Spain','flag'=>'🇪🇸'],
    ['code'=>'+94','country'=>'Sri Lanka','flag'=>'🇱🇰'],
    ['code'=>'+46','country'=>'Sweden','flag'=>'🇸🇪'],
    ['code'=>'+41','country'=>'Switzerland','flag'=>'🇨🇭'],
    ['code'=>'+66','country'=>'Thailand','flag'=>'🇹🇭'],
    ['code'=>'+90','country'=>'Turkey','flag'=>'🇹🇷'],
    ['code'=>'+971','country'=>'United Arab Emirates','flag'=>'🇦🇪'],
    ['code'=>'+44','country'=>'United Kingdom','flag'=>'🇬🇧'],
    ['code'=>'+1','country'=>'United States','flag'=>'🇺🇸'],
    ['code'=>'+84','country'=>'Vietnam','flag'=>'🇻🇳'],
    ['code'=>'+263','country'=>'Zimbabwe','flag'=>'🇿🇼'],
];
