<?php
return [
    'staticBrands' => [
        '2025' => [
            [
                "brand" => "3M Car Care",
                "logo" => "/topfranchiseleaders/staticLogo/2025/3mcarcare.jpg",
                "industry" => "Automotive",
                "sector" => "Car Wash / Ceramic Coating / Detailing",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Ather Energy",
                "logo" => "/topfranchiseleaders/staticLogo/2025/atherenergy.jpg",
                "industry" => "Automotive",
                "sector" => "Electric Vehicles Two Wheelers (EV)",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "BlueDart",
                "logo" => "/topfranchiseleaders/staticLogo/2025/bluedart.jpg",
                "industry" => "Business Services",
                "sector" => "Courier & Delivery",
                "investment" => "Rs. 2 Lakh - 5 Lakh",
            ],
            [
                "brand" => "Caratlane",
                "logo" => "/topfranchiseleaders/staticLogo/2025/caratlane.jpg",
                "industry" => "Fashion",
                "sector" => "Precious Jewellery",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "Crossword",
                "logo" => "/topfranchiseleaders/staticLogo/2025/crossword.jpg",
                "industry" => "Retail",
                "sector" => "Book Stores",
                "investment" => "Rs. 20 Lakh - 30 Lakh",
            ],
            [
                "brand" => "Heads up for Tails",
                "logo" => "/topfranchiseleaders/staticLogo/2025/headsupfortails.jpg",
                "industry" => "Retail",
                "sector" => "Pet Stores",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "Kalyan Jewellers",
                "logo" => "/topfranchiseleaders/staticLogo/2025/kalyanjewellers.jpg",
                "industry" => "Fashion",
                "sector" => "Precious Jewellery",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "Mahindra & Mahindra Financial Services Ltd",
                "logo" => "/topfranchiseleaders/staticLogo/2025/mahindramahindrafinancialservicesltd.jpg",
                "industry" => "Business Services",
                "sector" => "Finance Advisors & Brokers",
                "investment" => "Rs. 50000 - 2 Lakh",
            ],
            [
                "brand" => "Tata Power",
                "logo" => "/topfranchiseleaders/staticLogo/2025/tatapower.jpg",
                "industry" => "Automotive",
                "sector" => "Charging Stations",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "US POLO",
                "logo" => "/topfranchiseleaders/staticLogo/2025/uspolo.jpg",
                "industry" => "Fashion",
                "sector" => "Readymade",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Van Heusen",
                "logo" => "/topfranchiseleaders/staticLogo/2025/vanheusen.jpg",
                "industry" => "Fashion",
                "sector" => "Lingerie & Innerwear",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Behrouz Biryani",
                "logo" => "/topfranchiseleaders/staticLogo/2025/behrouzbiryani.jpg",
                "industry" => "Food And Beverage",
                "sector" => "Online Food Ordering Services",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Birla Opus",
                "logo" => "/topfranchiseleaders/staticLogo/2025/birlaopus.jpg",
                "industry" => "Dealers & Distributors",
                "sector" => "Paints & Allied Products",
                "investment" => "Rs. 20 Lakh - 30 Lakh",
            ],
            [
                "brand" => "Dr. Jamuna Pai's SkinLab",
                "logo" => "/topfranchiseleaders/staticLogo/2025/drjamunapaisskinlab.jpg",
                "industry" => "Beauty and Health",
                "sector" => "Healthcare Products",
                "investment" => "Rs. 20 Lakh - 30 Lakh",
            ],
            [
                "brand" => "Farzi Cafe",
                "logo" => "/topfranchiseleaders/staticLogo/2025/farzicafe.jpg",
                "industry" => "Food And Beverage",
                "sector" => "Fine Dine Restaurants",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "Fasoos",
                "logo" => "/topfranchiseleaders/staticLogo/2025/fasoos.jpg",
                "industry" => "Food And Beverage",
                "sector" => "Others Food Service",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Giva",
                "logo" => "/topfranchiseleaders/staticLogo/2025/giva.jpg",
                "industry" => "Fashion",
                "sector" => "Precious Jewellery",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Go Colors",
                "logo" => "/topfranchiseleaders/staticLogo/2025/gocolors.jpg",
                "industry" => "Fashion",
                "sector" => "Womens Wear",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Himalaya Opticals",
                "logo" => "/topfranchiseleaders/staticLogo/2025/himalayaopticals.jpg",
                "industry" => "Fashion",
                "sector" => "Opticians/Eye Wear",
                "investment" => "Rs. 20 Lakh - 30 Lakh",
            ],
            [
                "brand" => "Ironhill India",
                "logo" => "/topfranchiseleaders/staticLogo/2025/ironhillindia.jpg",
                "industry" => "Food And Beverage",
                "sector" => "Bars, Pubs & Lounge",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "John Players",
                "logo" => "/topfranchiseleaders/staticLogo/2025/johnplayers.jpg",
                "industry" => "Fashion",
                "sector" => "Readymade",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Lakme Academy",
                "logo" => "/topfranchiseleaders/staticLogo/2025/lakmeacademy.jpg",
                "industry" => "Education",
                "sector" => "Beauty & Wellness Training Institute",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "Lee Cooper",
                "logo" => "/topfranchiseleaders/staticLogo/2025/leecooper.jpg",
                "industry" => "Fashion",
                "sector" => "Readymade",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Lemon Tree",
                "logo" => "/topfranchiseleaders/staticLogo/2025/lemontree.jpg",
                "industry" => "Hotel, Travel & Tourism",
                "sector" => "Hotel Chain",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "Looks",
                "logo" => "/topfranchiseleaders/staticLogo/2025/looks.jpg",
                "industry" => "Beauty & Health",
                "sector" => "Beauty Salons/ Unisex Salons/ Spa",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "Madame",
                "logo" => "/topfranchiseleaders/staticLogo/2025/madame.jpg",
                "industry" => "Fashion",
                "sector" => "Womens Wear",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Ministry Of Beer",
                "logo" => "/topfranchiseleaders/staticLogo/2025/ministryofbeer.jpg",
                "industry" => "Food And Beverage",
                "sector" => "Bars, Pubs & Lounge",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "Moti Mahal Delux",
                "logo" => "/topfranchiseleaders/staticLogo/2025/motimahaldelux.jpg",
                "industry" => "Food And Beverage",
                "sector" => "Fine Dine Restaurants",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "Naturals",
                "logo" => "/topfranchiseleaders/staticLogo/2025/naturals.jpg",
                "industry" => "Food And Beverage",
                "sector" => "Ice Creams & Yogurt Parlors",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Sabhyata",
                "logo" => "/topfranchiseleaders/staticLogo/2025/sabhyata.jpg",
                "industry" => "Retail",
                "sector" => "Women's Clothing",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Saravana Bhavan",
                "logo" => "/topfranchiseleaders/staticLogo/2025/saravanabhavan.jpg",
                "industry" => "Food And Beverage",
                "sector" => "Quick Service Restaurants",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Shallby Hospitals",
                "logo" => "/topfranchiseleaders/staticLogo/2025/shallbyhospitals.jpg",
                "industry" => "Beauty & Health",
                "sector" => "Hospitals",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "Shree",
                "logo" => "/topfranchiseleaders/staticLogo/2025/shree.jpg",
                "industry" => "Retail",
                "sector" => "Women's Clothing",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Swiggy Instamart",
                "logo" => "/topfranchiseleaders/staticLogo/2025/swiggyinstamart.jpg",
                "industry" => "Retail",
                "sector" => "E-Commerce & Related",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "The Pilates Studio",
                "logo" => "/topfranchiseleaders/staticLogo/2025/thepilatesstudio.jpg",
                "industry" => "Retail",
                "sector" => "Gyms And Fitness Centres",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "Aurelia",
                "logo" => "/topfranchiseleaders/staticLogo/2025/aurelia.jpg",
                "industry" => "Fashion",
                "sector" => "Womens Wear",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "Bhaichung Bhutia",
                "logo" => "/topfranchiseleaders/staticLogo/2025/bhaichungbhutia.jpg",
                "industry" => "Sports, Fitness & Entertainment",
                "sector" => "Sports & Gaming",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "Bonjour",
                "logo" => "/topfranchiseleaders/staticLogo/2025/bonjour.jpg",
                "industry" => "Fashion",
                "sector" => "Others Clothing",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            // [
            //     "brand" => "Clovia",
            //     "logo" => "/topfranchiseleaders/staticLogo/2025/clovia.jpg",
            //     "industry" => "Fashion",
            //     "sector" => "Lingerie & Innerwear",
            //     "investment" => "Rs. 20 Lakh - 30 Lakh",
            // ],
            [
                "brand" => "Dhaba",
                "logo" => "/topfranchiseleaders/staticLogo/2025/dhaba.jpg",
                "industry" => "Food And Beverage",
                "sector" => "Fine Dine Restaurants",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "Reliance Fashion World",
                "logo" => "/topfranchiseleaders/staticLogo/2025/reliancefashionworld.jpg",
                "industry" => "Fashion",
                "sector" => "Departmental/Unisex",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "Trends Footwear",
                "logo" => "/topfranchiseleaders/staticLogo/2025/trendsfootwear.jpg",
                "industry" => "Fashion",
                "sector" => "Casuals",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Gargi by PNGS",
                "logo" => "/topfranchiseleaders/staticLogo/2025/gargibypngs.jpg",
                "industry" => "Fashion",
                "sector" => "Precious Jewellery",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "Mama Goto",
                "logo" => "/topfranchiseleaders/staticLogo/2025/mamagoto.jpg",
                "industry" => "Food And Beverage",
                "sector" => "Casual Dine Restaurants",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "Bodycraft Salon",
                "logo" => "/topfranchiseleaders/staticLogo/2025/bodycraftsalon.jpg",
                "industry" => "Beauty & Health",
                "sector" => "Beauty Salons/ Unisex Salons/ Spa",
                "investment" => "Rs. 2 Cr - 5 Cr",
            ],
            [
                "brand" => "Non Stop",
                "logo" => "/topfranchiseleaders/staticLogo/2025/nonstop.jpg",
                "industry" => "Beauty & Health",
                "sector" => "Healthcare Products",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "Oliva Skin and Hair Clinics",
                "logo" => "/topfranchiseleaders/staticLogo/2025/olivaskinandhairclinics.jpg",
                "industry" => "Beauty & Health",
                "sector" => "Clinics & Nursing Homes",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "Pigeon by Stovekraft",
                "logo" => "/topfranchiseleaders/staticLogo/2025/pigeonbystovekraft.jpg",
                "industry" => "Retail",
                "sector" => "Kitchen",
                "investment" => "Rs. 20 Lakh - 30 Lakh",
            ],
            [
                "brand" => "Portico",
                "logo" => "/topfranchiseleaders/staticLogo/2025/portico.jpg",
                "industry" => "Retail",
                "sector" => "Furniture/Home Decor & Furnishing",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "PVR INOX",
                "logo" => "/topfranchiseleaders/staticLogo/2025/pvrinox.jpg",
                "industry" => "Sports, Fitness & Entertainment",
                "sector" => "Movies (Multiplex)",
                "investment" => "Rs. 2 Cr - 5 Cr",
            ],
            [
                "brand" => "Soliatrio",
                "logo" => "/topfranchiseleaders/staticLogo/2025/soliatrio.jpg",
                "industry" => "Fashion",
                "sector" => "Precious Jewellery",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "The Ofen Bakery",
                "logo" => "/topfranchiseleaders/staticLogo/2025/theofenbakery.jpg",
                "industry" => "Food And Beverage",
                "sector" => "Bakery & Confectionary",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Adidas",
                "logo" => "/topfranchiseleaders/staticLogo/2025/adidas.jpg",
                "industry" => "Fashion",
                "sector" => "Sports",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Domino's",
                "logo" => "/topfranchiseleaders/staticLogo/2025/dominos.jpg",
                "industry" => "Food And Beverage",
                "sector" => "Pizzeria",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "Hyatt",
                "logo" => "/topfranchiseleaders/staticLogo/2025/hyatt.jpg",
                "industry" => "Hotel, Travel & Tourism",
                "sector" => "Hotel Chain",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "Marriott",
                "logo" => "/topfranchiseleaders/staticLogo/2025/marriott.jpg",
                "industry" => "Hotel, Travel & Tourism",
                "sector" => "Hotel Chain",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "Nike",
                "logo" => "/topfranchiseleaders/staticLogo/2025/nike.jpg",
                "industry" => "Fashion",
                "sector" => "Sports",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "Puma",
                "logo" => "/topfranchiseleaders/staticLogo/2025/puma.jpg",
                "industry" => "Fashion",
                "sector" => "Sports",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Reebok",
                "logo" => "/topfranchiseleaders/staticLogo/2025/reebok.jpg",
                "industry" => "Fashion",
                "sector" => "Sports",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "Wyndham",
                "logo" => "/topfranchiseleaders/staticLogo/2025/wyndham.jpg",
                "industry" => "Hotel, Travel & Tourism",
                "sector" => "Hotel Chain",
                "investment" => "Rs. 5 Cr above",
            ],
        ],
        '2024' => [

            [
                "brand" => "Kotak Securities",
                "logo" => "/topfranchiseleaders/staticLogo/2024/kotaksecurities.webp",
                "industry" => "Business Services",
                "sector" => "Financial Investment & Trading",
                "investment" => "Rs. 50 K - 2 Lakh",
            ],
            [
                "brand" => "US POLO",
                "logo" => "/topfranchiseleaders/staticLogo/2024/uspolo.webp",
                "industry" => "Retail",
                "sector" => "Men's Footwear",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "W by TCNS",
                "logo" => "/topfranchiseleaders/staticLogo/2024/wbytcns.webp",
                "industry" => "Retail",
                "sector" => "Women's Clothing",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Caratlane",
                "logo" => "/topfranchiseleaders/staticLogo/2024/caratlane.webp",
                "industry" => "Retail",
                "sector" => "Designer Jewellery",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "Mamagoto",
                "logo" => "/topfranchiseleaders/staticLogo/2024/mamagoto.webp",
                "industry" => "Food & Beverage",
                "sector" => "Quick Service Restaurants",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "Kalyan Jewellers",
                "logo" => "/topfranchiseleaders/staticLogo/2024/kalyanjewellers.webp",
                "industry" => "Retail",
                "sector" => "Designer Jewellery",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "Cultfit",
                "logo" => "/topfranchiseleaders/staticLogo/2024/cultfit.webp",
                "industry" => "Beauty & Health",
                "sector" => "Beauty Salons/ Unisex Salons/ Spa",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "Lemon Tree",
                "logo" => "/topfranchiseleaders/staticLogo/2024/lemontree.webp",
                "industry" => "Hotel, Travel & Tourism",
                "sector" => "Hotel Chain",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "Crossword",
                "logo" => "/topfranchiseleaders/staticLogo/2024/crossword.webp",
                "industry" => "Retail",
                "sector" => "Book Stores",
                "investment" => "Rs. 20 Lakh - 30 Lakh",
            ],
            [
                "brand" => "Ather",
                "logo" => "/topfranchiseleaders/staticLogo/2024/ather.webp",
                "industry" => "Automotive",
                "sector" => "Electric Vehicles Two Wheelers (EV)",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "Go Colors",
                "logo" => "/topfranchiseleaders/staticLogo/2024/gocolors.webp",
                "industry" => "Fashion",
                "sector" => "Readymade",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Heads up For Tails",
                "logo" => "/topfranchiseleaders/staticLogo/2024/headsupfortails.webp",
                "industry" => "Retail",
                "sector" => "Pet Stores",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "Mothers Pride",
                "logo" => "/topfranchiseleaders/staticLogo/2024/motherspride.webp",
                "industry" => "Education",
                "sector" => "Preschools",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "Prakruthi",
                "logo" => "/topfranchiseleaders/staticLogo/2024/prakruthi.webp",
                "industry" => "Education",
                "sector" => "School Tutoring",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "Hippo Stores",
                "logo" => "/topfranchiseleaders/staticLogo/2024/hippostores.webp",
                "industry" => "Retail",
                "sector" => "Department & Convenience Stores",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Puma",
                "logo" => "/topfranchiseleaders/staticLogo/2024/puma.webp",
                "industry" => "Retail",
                "sector" => "Men's Footwear",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Domino's Pizza",
                "logo" => "/topfranchiseleaders/staticLogo/2024/dominos.webp",
                "industry" => "Food & Beverage",
                "sector" => "Quick Service Restaurants",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "Reebok",
                "logo" => "/topfranchiseleaders/staticLogo/2024/reebok.webp",
                "industry" => "Retail",
                "sector" => "Men's Footwear",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "Elle Décor Kitchens",
                "logo" => "/topfranchiseleaders/staticLogo/2024/elledecorkitchens.webp",
                "industry" => "Retail",
                "sector" => "Kitchen",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Marriott International",
                "logo" => "/topfranchiseleaders/staticLogo/2024/marriott.webp",
                "industry" => "Hotel, Travel & Tourism",
                "sector" => "Hotel Chain",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "Hyatt",
                "logo" => "/topfranchiseleaders/staticLogo/2024/hyatt.webp",
                "industry" => "Hotel, Travel & Tourism",
                "sector" => "Hotel Chain",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "Wyndhamm Hotel & Resorts",
                "logo" => "/topfranchiseleaders/staticLogo/2024/wyndham.webp",
                "industry" => "Hotel, Travel & Tourism",
                "sector" => "Hotel Chain",
                "investment" => "Rs. 5 Cr above",
            ],
        ],
        '2023' => [
            [
                "brand" => "3M Car Care",
                "logo" => "/topfranchiseleaders/staticLogo/2023/3mcarcare.webp",
                "industry" => "Automotive",
                "sector" => "Automobile Accessories",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "AND",
                "logo" => "/topfranchiseleaders/staticLogo/2023/and.webp",
                "industry" => "Fashion",
                "sector" => "Womens Wear",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Kotak Securities",
                "logo" => "/topfranchiseleaders/staticLogo/2023/kotak.webp",
                "industry" => "Business Services",
                "sector" => "Financial Investment & Trading",
                "investment" => "Rs. 50 K - 2 Lakh",
            ],
            [
                "brand" => "Bhaichung Bhutia Football Schools",
                "logo" => "/topfranchiseleaders/staticLogo/2023/bhaichungbhutia.webp",
                "industry" => "Sports, Fitness & Entertainment",
                "sector" => "Sports & Gaming",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "Caratlane",
                "logo" => "/topfranchiseleaders/staticLogo/2023/caratlane.webp",
                "industry" => "Retail",
                "sector" => "Designer Jewellery",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "Dhaba by Claridges",
                "logo" => "/topfranchiseleaders/staticLogo/2023/dhaba.webp",
                "industry" => "Food & Beverage",
                "sector" => "Fine Dine Restaurants",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "Hero Electric",
                "logo" => "/topfranchiseleaders/staticLogo/2023/heroelectric.webp",
                "industry" => "Automotive",
                "sector" => "Electric Vehicles Two Wheelers (EV)",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Joyalukkas",
                "logo" => "/topfranchiseleaders/staticLogo/2023/joyalukkas.webp",
                "industry" => "Retail",
                "sector" => "Designer Jewellery",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "Loom Solar",
                "logo" => "/topfranchiseleaders/staticLogo/2023/loomsolar.webp",
                "industry" => "Dealers & Distributors",
                "sector" => "Solar Products",
                "investment" => "Rs. 2 Lakh - 5 Lakh",
            ],
            [
                "brand" => "Mamagoto",
                "logo" => "/topfranchiseleaders/staticLogo/2023/mama.webp",
                "industry" => "Food & Beverage",
                "sector" => "Casual Dine Restaurants",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "US POLO",
                "logo" => "/topfranchiseleaders/staticLogo/2023/uspolo.webp",
                "industry" => "Fashion",
                "sector" => "Readymade",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "W by TCNS",
                "logo" => "/topfranchiseleaders/staticLogo/2023/wbytcns.webp",
                "industry" => "Fashion",
                "sector" => "Womens Wear",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Babai Hotels",
                "logo" => "/topfranchiseleaders/staticLogo/2023/babaihotels.webp",
                "industry" => "Food & Beverage",
                "sector" => "Quick Service Restaurants",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "Cloud Dhaba",
                "logo" => "/topfranchiseleaders/staticLogo/2023/clouddhaba.webp",
                "industry" => "Food & Beverage",
                "sector" => "Fine Dine Restaurants",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "Heads up For Tails",
                "logo" => "/topfranchiseleaders/staticLogo/2023/headsupfortails.webp",
                "industry" => "Retail",
                "sector" => "Pet Stores",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "Innov8",
                "logo" => "/topfranchiseleaders/staticLogo/2023/innov8.webp",
                "industry" => "Business Services",
                "sector" => "Real Estate Sub",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "Mahesh Bhupathi Tennis Academy",
                "logo" => "/topfranchiseleaders/staticLogo/2023/maheshbhupathitennisacademy.webp",
                "industry" => "Sports, Fitness & Entertainment",
                "sector" => "Sports & Gaming",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Mystery Rooms",
                "logo" => "/topfranchiseleaders/staticLogo/2023/mysteryrooms.webp",
                "industry" => "Sports, Fitness & Entertainment",
                "sector" => "Sports & Gaming",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Dale Carnegie",
                "logo" => "/topfranchiseleaders/staticLogo/2023/dalecarnegie.webp",
                "industry" => "Education",
                "sector" => "Corporate Training",
                "investment" => "Rs. 5 Lakh - 10 Lakh",
            ],
            [
                "brand" => "Adidas",
                "logo" => "/topfranchiseleaders/staticLogo/2023/adidas.webp",
                "industry" => "Fashion",
                "sector" => "Sports",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Domino's Pizza",
                "logo" => "/topfranchiseleaders/staticLogo/2023/domino's.webp",
                "industry" => "Food & Beverage",
                "sector" => "Pizzeria",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "Hyatt",
                "logo" => "/topfranchiseleaders/staticLogo/2023/hyatt.webp",
                "industry" => "Hotel Travel & Tourism",
                "sector" => "Hotel Chain",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "Puma",
                "logo" => "/topfranchiseleaders/staticLogo/2023/puma.webp",
                "industry" => "Fashion",
                "sector" => "Sports",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
        ],


    ],


];
