<?php
return [
    'staticBrands' => [
        [
            "brand" => "3M Car Care",
            "logo" => "/topfranchiseleaders/staticLogo/3mcarcare.jpg",
            "industry" => "Automotive",
            "sector" => "Car Wash / Ceramic Coating / Detailing",
            "investment" => "Rs. 30 Lakh - 50 Lakh",
        ],
        [
            "brand" => "Ather Energy",
            "logo" => "/topfranchiseleaders/staticLogo/atherenergy.jpg",
            "industry" => "Automotive",
            "sector" => "Electric Vehicles Two Wheelers (EV)",
            "investment" => "Rs. 5 Cr above",
        ],
        [
            "brand" => "BlueDart",
            "logo" => "/topfranchiseleaders/staticLogo/bluedart.jpg",
            "industry" => "Business Services",
            "sector" => "Courier & Delivery",
            "investment" => "Rs. 2 Lakh - 5 Lakh",
        ],
        [
            "brand" => "Caratlane",
            "logo" => "/topfranchiseleaders/staticLogo/caratlane.jpg",
            "industry" => "Fashion",
            "sector" => "Precious Jewellery",
            "investment" => "Rs. 1 Cr - 2 Cr",
        ],
        [
            "brand" => "Crossword",
            "logo" => "/topfranchiseleaders/staticLogo/crossword.jpg",
            "industry" => "Retail",
            "sector" => "Book Stores",
            "investment" => "Rs. 20 Lakh - 30 Lakh",
        ],
        [
            "brand" => "Heads up for Tails",
            "logo" => "/topfranchiseleaders/staticLogo/headsupfortails.jpg",
            "industry" => "Retail",
            "sector" => "Pet Stores",
            "investment" => "Rs. 10 Lakh - 20 Lakh",
        ],
        [
            "brand" => "Kalyan Jewellers",
            "logo" => "/topfranchiseleaders/staticLogo/kalyanjewellers.jpg",
            "industry" => "Fashion",
            "sector" => "Precious Jewellery",
            "investment" => "Rs. 5 Cr above",
        ],
        [
            "brand" => "Mahindra & Mahindra Financial Services Ltd",
            "logo" => "/topfranchiseleaders/staticLogo/mahindramahindrafinancialservicesltd.jpg",
            "industry" => "Business Services",
            "sector" => "Finance Advisors & Brokers",
            "investment" => "Rs. 50000 - 2 Lakh",
        ],
        [
            "brand" => "Tata Power",
            "logo" => "/topfranchiseleaders/staticLogo/tatapower.jpg",
            "industry" => "Automotive",
            "sector" => "Charging Stations",
            "investment" => "Rs. 1 Cr - 2 Cr",
        ],
        [
            "brand" => "US POLO",
            "logo" => "/topfranchiseleaders/staticLogo/uspolo.jpg",
            "industry" => "Fashion",
            "sector" => "Readymade",
            "investment" => "Rs. 30 Lakh - 50 Lakh",
        ],
        [
            "brand" => "Van Heusen",
            "logo" => "/topfranchiseleaders/staticLogo/vanheusen.jpg",
            "industry" => "Fashion",
            "sector" => "Lingerie & Innerwear",
            "investment" => "Rs. 30 Lakh - 50 Lakh",
        ],
        [
            "brand" => "Behrouz Biryani",
            "logo" => "/topfranchiseleaders/staticLogo/behrouzbiryani.jpg",
            "industry" => "Food And Beverage",
            "sector" => "Online Food Ordering Services",
            "investment" => "Rs. 30 Lakh - 50 Lakh",
        ],
        [
            "brand" => "Birla Opus",
            "logo" => "/topfranchiseleaders/staticLogo/birlaopus.jpg",
            "industry" => "Dealers & Distributors",
            "sector" => "Paints & Allied Products",
            "investment" => "Rs. 20 Lakh - 30 Lakh",
        ],
        [
            "brand" => "Dr. Jamuna Pai's SkinLab",
            "logo" => "/topfranchiseleaders/staticLogo/drjamunapaisskinlab.jpg",
            "industry" => "Beauty and Health",
            "sector" => "Healthcare Products",
            "investment" => "Rs. 20 Lakh - 30 Lakh",
        ],
        [
            "brand" => "Farzi Cafe",
            "logo" => "/topfranchiseleaders/staticLogo/farzicafe.jpg",
            "industry" => "Food And Beverage",
            "sector" => "Fine Dine Restaurants",
            "investment" => "Rs. 50 Lakh - 1 Cr",
        ],
        [
            "brand" => "Fasoos",
            "logo" => "/topfranchiseleaders/staticLogo/fasoos.jpg",
            "industry" => "Food And Beverage",
            "sector" => "Others Food Service",
            "investment" => "Rs. 30 Lakh - 50 Lakh",
        ],
        [
            "brand" => "Giva",
            "logo" => "/topfranchiseleaders/staticLogo/giva.jpg",
            "industry" => "Fashion",
            "sector" => "Precious Jewellery",
            "investment" => "Rs. 30 Lakh - 50 Lakh",
        ],
        [
            "brand" => "Go Colors",
            "logo" => "/topfranchiseleaders/staticLogo/gocolors.jpg",
            "industry" => "Fashion",
            "sector" => "Womens Wear",
            "investment" => "Rs. 30 Lakh - 50 Lakh",
        ],
        [
            "brand" => "Himalaya Opticals",
            "logo" => "/topfranchiseleaders/staticLogo/himalayaopticals.jpg",
            "industry" => "Fashion",
            "sector" => "Opticians/Eye Wear",
            "investment" => "Rs. 20 Lakh - 30 Lakh",
        ],
        [
            "brand" => "Ironhill India",
            "logo" => "/topfranchiseleaders/staticLogo/ironhillindia.jpg",
            "industry" => "Food And Beverage",
            "sector" => "Bars, Pubs & Lounge",
            "investment" => "Rs. 5 Cr above",
        ],
        [
            "brand" => "John Players",
            "logo" => "/topfranchiseleaders/staticLogo/johnplayers.jpg",
            "industry" => "Fashion",
            "sector" => "Readymade",
            "investment" => "Rs. 30 Lakh - 50 Lakh",
        ],
        [
            "brand" => "Lakme Academy",
            "logo" => "/topfranchiseleaders/staticLogo/lakmeacademy.jpg",
            "industry" => "Education",
            "sector" => "Beauty & Wellness Training Institute",
            "investment" => "Rs. 50 Lakh - 1 Cr",
        ],
        [
            "brand" => "Lee Cooper",
            "logo" => "/topfranchiseleaders/staticLogo/leecooper.jpg",
            "industry" => "Fashion",
            "sector" => "Readymade",
            "investment" => "Rs. 30 Lakh - 50 Lakh",
        ],
        [
            "brand" => "Lemon Tree",
            "logo" => "/topfranchiseleaders/staticLogo/lemontree.jpg",
            "industry" => "Hotel, Travel & Tourism",
            "sector" => "Hotel Chain",
            "investment" => "Rs. 5 Cr above",
        ],
        [
            "brand" => "Looks",
            "logo" => "/topfranchiseleaders/staticLogo/looks.jpg",
            "industry" => "Beauty & Health",
            "sector" => "Beauty Salons/ Unisex Salons/ Spa",
            "investment" => "Rs. 1 Cr - 2 Cr",
        ],
        [
            "brand" => "Madame",
            "logo" => "/topfranchiseleaders/staticLogo/madame.jpg",
            "industry" => "Fashion",
            "sector" => "Womens Wear",
            "investment" => "Rs. 30 Lakh - 50 Lakh",
        ],
        [
            "brand" => "Ministry Of Beer",
            "logo" => "/topfranchiseleaders/staticLogo/ministryofbeer.jpg",
            "industry" => "Food And Beverage",
            "sector" => "Bars, Pubs & Lounge",
            "investment" => "Rs. 1 Cr - 2 Cr",
        ],
        [
            "brand" => "Moti Mahal Delux",
            "logo" => "/topfranchiseleaders/staticLogo/motimahaldelux.jpg",
            "industry" => "Food And Beverage",
            "sector" => "Fine Dine Restaurants",
            "investment" => "Rs. 50 Lakh - 1 Cr",
        ],
        [
            "brand" => "Naturals",
            "logo" => "/topfranchiseleaders/staticLogo/naturals.jpg",
            "industry" => "Food And Beverage",
            "sector" => "Ice Creams & Yogurt Parlors",
            "investment" => "Rs. 30 Lakh - 50 Lakh",
        ],
        [
            "brand" => "Sabhyata",
            "logo" => "/topfranchiseleaders/staticLogo/sabhyata.jpg",
            "industry" => "Retail",
            "sector" => "Women's Clothing",
            "investment" => "Rs. 30 Lakh - 50 Lakh",
        ],
        [
            "brand" => "Saravana Bhavan",
            "logo" => "/topfranchiseleaders/staticLogo/saravanabhavan.jpg",
            "industry" => "Food And Beverage",
            "sector" => "Quick Service Restaurants",
            "investment" => "Rs. 30 Lakh - 50 Lakh",
        ],
        [
            "brand" => "Shallby Hospitals",
            "logo" => "/topfranchiseleaders/staticLogo/shallbyhospitals.jpg",
            "industry" => "Beauty & Health",
            "sector" => "Hospitals",
            "investment" => "Rs. 5 Cr above",
        ],
        [
            "brand" => "Shree",
            "logo" => "/topfranchiseleaders/staticLogo/shree.jpg",
            "industry" => "Retail",
            "sector" => "Women's Clothing",
            "investment" => "Rs. 30 Lakh - 50 Lakh",
        ],
        [
            "brand" => "Swiggy Instamart",
            "logo" => "/topfranchiseleaders/staticLogo/swiggyinstamart.jpg",
            "industry" => "Retail",
            "sector" => "E-Commerce & Related",
            "investment" => "Rs. 50 Lakh - 1 Cr",
        ],
        [
            "brand" => "The Pilates Studio",
            "logo" => "/topfranchiseleaders/staticLogo/thepilatesstudio.jpg",
            "industry" => "Retail",
            "sector" => "Gyms And Fitness Centres",
            "investment" => "Rs. 50 Lakh - 1 Cr",
        ],
        [
            "brand" => "Aurelia",
            "logo" => "/topfranchiseleaders/staticLogo/aurelia.jpg",
            "industry" => "Fashion",
            "sector" => "Womens Wear",
            "investment" => "Rs. 50 Lakh - 1 Cr",
        ],
        [
            "brand" => "Bhaichung Bhutia",
            "logo" => "/topfranchiseleaders/staticLogo/bhaichungbhutia.jpg",
            "industry" => "Sports, Fitness & Entertainment",
            "sector" => "Sports & Gaming",
            "investment" => "Rs. 10 Lakh - 20 Lakh",
        ],
        [
            "brand" => "Bonjour",
            "logo" => "/topfranchiseleaders/staticLogo/bonjour.jpg",
            "industry" => "Fashion",
            "sector" => "Others Clothing",
            "investment" => "Rs. 10 Lakh - 20 Lakh",
        ],
        [
            "brand" => "Clovia",
            "logo" => "/topfranchiseleaders/staticLogo/clovia.jpg",
            "industry" => "Fashion",
            "sector" => "Lingerie & Innerwear",
            "investment" => "Rs. 20 Lakh - 30 Lakh",
        ],
        [
            "brand" => "Dhaba",
            "logo" => "/topfranchiseleaders/staticLogo/dhaba.jpg",
            "industry" => "Food And Beverage",
            "sector" => "Fine Dine Restaurants",
            "investment" => "Rs. 1 Cr - 2 Cr",
        ],
        [
            "brand" => "Reliance Fashion World",
            "logo" => "/topfranchiseleaders/staticLogo/reliancefashionworld.jpg",
            "industry" => "Fashion",
            "sector" => "Departmental/Unisex",
            "investment" => "Rs. 50 Lakh - 1 Cr",
        ],
        [
            "brand" => "Trends Footwear",
            "logo" => "/topfranchiseleaders/staticLogo/trendsfootwear.jpg",
            "industry" => "Fashion",
            "sector" => "Casuals",
            "investment" => "Rs. 30 Lakh - 50 Lakh",
        ],
        [
            "brand" => "Gargi by PNGS",
            "logo" => "/topfranchiseleaders/staticLogo/gargibypngs.jpg",
            "industry" => "Fashion",
            "sector" => "Precious Jewellery",
            "investment" => "Rs. 50 Lakh - 1 Cr",
        ],
        [
            "brand" => "Mama Goto",
            "logo" => "/topfranchiseleaders/staticLogo/mamagoto.jpg",
            "industry" => "Food And Beverage",
            "sector" => "Casual Dine Restaurants",
            "investment" => "Rs. 1 Cr - 2 Cr",
        ],
        [
            "brand" => "Bodycraft Salon",
            "logo" => "/topfranchiseleaders/staticLogo/bodycraftsalon.jpg",
            "industry" => "Beauty & Health",
            "sector" => "Beauty Salons/ Unisex Salons/ Spa",
            "investment" => "Rs. 2 Cr - 5 Cr",
        ],
        [
            "brand" => "Non Stop",
            "logo" => "/topfranchiseleaders/staticLogo/nonstop.jpg",
            "industry" => "Beauty & Health",
            "sector" => "Healthcare Products",
            "investment" => "Rs. 50 Lakh - 1 Cr",
        ],
        [
            "brand" => "Oliva Skin and Hair Clinics",
            "logo" => "/topfranchiseleaders/staticLogo/olivaskinandhairclinics.jpg",
            "industry" => "Beauty & Health",
            "sector" => "Clinics & Nursing Homes",
            "investment" => "Rs. 1 Cr - 2 Cr",
        ],
        [
            "brand" => "Pigeon by Stovekraft",
            "logo" => "/topfranchiseleaders/staticLogo/pigeonbystovekraft.jpg",
            "industry" => "Retail",
            "sector" => "Kitchen",
            "investment" => "Rs. 20 Lakh - 30 Lakh",
        ],
        [
            "brand" => "Portico",
            "logo" => "/topfranchiseleaders/staticLogo/portico.jpg",
            "industry" => "Retail",
            "sector" => "Furniture/Home Decor & Furnishing",
            "investment" => "Rs. 30 Lakh - 50 Lakh",
        ],
        [
            "brand" => "PVR INOX",
            "logo" => "/topfranchiseleaders/staticLogo/pvrinox.jpg",
            "industry" => "Sports, Fitness & Entertainment",
            "sector" => "Movies (Multiplex)",
            "investment" => "Rs. 2 Cr - 5 Cr",
        ],
        [
            "brand" => "Soliatrio",
            "logo" => "/topfranchiseleaders/staticLogo/soliatrio.jpg",
            "industry" => "Fashion",
            "sector" => "Precious Jewellery",
            "investment" => "Rs. 50 Lakh - 1 Cr",
        ],
        [
            "brand" => "The Ofen Bakery",
            "logo" => "/topfranchiseleaders/staticLogo/theofenbakery.jpg",
            "industry" => "Food And Beverage",
            "sector" => "Bakery & Confectionary",
            "investment" => "Rs. 30 Lakh - 50 Lakh",
        ],
        [
            "brand" => "Adidas",
            "logo" => "/topfranchiseleaders/staticLogo/adidas.jpg",
            "industry" => "Fashion",
            "sector" => "Sports",
            "investment" => "Rs. 30 Lakh - 50 Lakh",
        ],
        [
            "brand" => "Domino's",
            "logo" => "/topfranchiseleaders/staticLogo/dominos.jpg",
            "industry" => "Food And Beverage",
            "sector" => "Pizzeria",
            "investment" => "Rs. 1 Cr - 2 Cr",
        ],
        [
            "brand" => "Hyatt",
            "logo" => "/topfranchiseleaders/staticLogo/hyatt.jpg",
            "industry" => "Hotel, Travel & Tourism",
            "sector" => "Hotel Chain",
            "investment" => "Rs. 5 Cr above",
        ],
        [
            "brand" => "Marriott",
            "logo" => "/topfranchiseleaders/staticLogo/marriott.jpg",
            "industry" => "Hotel, Travel & Tourism",
            "sector" => "Hotel Chain",
            "investment" => "Rs. 5 Cr above",
        ],
        [
            "brand" => "Nike",
            "logo" => "/topfranchiseleaders/staticLogo/nike.jpg",
            "industry" => "Fashion",
            "sector" => "Sports",
            "investment" => "Rs. 50 Lakh - 1 Cr",
        ],
        [
            "brand" => "Puma",
            "logo" => "/topfranchiseleaders/staticLogo/puma.jpg",
            "industry" => "Fashion",
            "sector" => "Sports",
            "investment" => "Rs. 30 Lakh - 50 Lakh",
        ],
        [
            "brand" => "Reebok",
            "logo" => "/topfranchiseleaders/staticLogo/reebok.jpg",
            "industry" => "Fashion",
            "sector" => "Sports",
            "investment" => "Rs. 50 Lakh - 1 Cr",
        ],
        [
            "brand" => "Wyndham",
            "logo" => "/topfranchiseleaders/staticLogo/wyndham.jpg",
            "industry" => "Hotel, Travel & Tourism",
            "sector" => "Hotel Chain",
            "investment" => "Rs. 5 Cr above",
        ],
    ]
];
