<?php
return [
    'staticBrands' => [
        '2025' => [
            [
                "brand" => "Ather Energy",
                "logo" => "/topfranchiseleaders/staticLogo/2025/atherenergy.jpg",
                "industry" => "Automotive",
                "sector" => "Electric Vehicles Two Wheelers (EV)",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "Caratlane",
                "logo" => "/topfranchiseleaders/staticLogo/2025/caratlane.jpg",
                "industry" => "Fashion",
                "sector" => "Precious Jewellery",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "Crossword",
                "logo" => "/topfranchiseleaders/staticLogo/2025/crossword.jpg",
                "industry" => "Retail",
                "sector" => "Book Stores",
                "investment" => "Rs. 20 Lakh - 30 Lakh",
            ],
            [
                "brand" => "Heads up for Tails",
                "logo" => "/topfranchiseleaders/staticLogo/2025/headsupfortails.jpg",
                "industry" => "Retail",
                "sector" => "Pet Stores",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "Mahindra & Mahindra Financial Services Ltd",
                "logo" => "/topfranchiseleaders/staticLogo/2025/mahindramahindrafinancialservicesltd.jpg",
                "industry" => "Business Services",
                "sector" => "Finance Advisors & Brokers",
                "investment" => "Rs. 50000 - 2 Lakh",
            ],
            [
                "brand" => "Tata Power",
                "logo" => "/topfranchiseleaders/staticLogo/2025/tatapower.jpg",
                "industry" => "Automotive",
                "sector" => "Charging Stations",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "US POLO",
                "logo" => "/topfranchiseleaders/staticLogo/2025/uspolo.jpg",
                "industry" => "Fashion",
                "sector" => "Readymade",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Van Heusen",
                "logo" => "/topfranchiseleaders/staticLogo/2025/vanheusen.jpg",
                "industry" => "Fashion",
                "sector" => "Lingerie & Innerwear",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Behrouz Biryani",
                "logo" => "/topfranchiseleaders/staticLogo/2025/behrouzbiryani.jpg",
                "industry" => "Food And Beverage",
                "sector" => "Online Food Ordering Services",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Birla Opus",
                "logo" => "/topfranchiseleaders/staticLogo/2025/birlaopus.jpg",
                "industry" => "Dealers & Distributors",
                "sector" => "Paints & Allied Products",
                "investment" => "Rs. 20 Lakh - 30 Lakh",
            ],
            [
                "brand" => "Dr. Jamuna Pai's SkinLab",
                "logo" => "/topfranchiseleaders/staticLogo/2025/drjamunapaisskinlab.jpg",
                "industry" => "Beauty and Health",
                "sector" => "Healthcare Products",
                "investment" => "Rs. 20 Lakh - 30 Lakh",
            ],
            [
                "brand" => "Farzi Cafe",
                "logo" => "/topfranchiseleaders/staticLogo/2025/farzicafe.jpg",
                "industry" => "Food And Beverage",
                "sector" => "Fine Dine Restaurants",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "Fasoos",
                "logo" => "/topfranchiseleaders/staticLogo/2025/fasoos.jpg",
                "industry" => "Food And Beverage",
                "sector" => "Others Food Service",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Go Colors",
                "logo" => "/topfranchiseleaders/staticLogo/2025/gocolors.jpg",
                "industry" => "Fashion",
                "sector" => "Womens Wear",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Himalaya Opticals",
                "logo" => "/topfranchiseleaders/staticLogo/2025/himalayaopticals.jpg",
                "industry" => "Fashion",
                "sector" => "Opticians/Eye Wear",
                "investment" => "Rs. 20 Lakh - 30 Lakh",
            ],
            [
                "brand" => "Ironhill India",
                "logo" => "/topfranchiseleaders/staticLogo/2025/ironhillindia.jpg",
                "industry" => "Food And Beverage",
                "sector" => "Bars, Pubs & Lounge",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "John Players",
                "logo" => "/topfranchiseleaders/staticLogo/2025/johnplayers.jpg",
                "industry" => "Fashion",
                "sector" => "Readymade",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Lee Cooper",
                "logo" => "/topfranchiseleaders/staticLogo/2025/leecooper.jpg",
                "industry" => "Fashion",
                "sector" => "Readymade",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Lemon Tree",
                "logo" => "/topfranchiseleaders/staticLogo/2025/lemontree.jpg",
                "industry" => "Hotel, Travel & Tourism",
                "sector" => "Hotel Chain",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "Looks",
                "logo" => "/topfranchiseleaders/staticLogo/2025/looks.jpg",
                "industry" => "Beauty & Health",
                "sector" => "Beauty Salons/ Unisex Salons/ Spa",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "Madame",
                "logo" => "/topfranchiseleaders/staticLogo/2025/madame.jpg",
                "industry" => "Fashion",
                "sector" => "Womens Wear",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Ministry Of Beer",
                "logo" => "/topfranchiseleaders/staticLogo/2025/ministryofbeer.jpg",
                "industry" => "Food And Beverage",
                "sector" => "Bars, Pubs & Lounge",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "Moti Mahal Delux",
                "logo" => "/topfranchiseleaders/staticLogo/2025/motimahaldelux.jpg",
                "industry" => "Food And Beverage",
                "sector" => "Fine Dine Restaurants",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "Naturals",
                "logo" => "/topfranchiseleaders/staticLogo/2025/naturals.jpg",
                "industry" => "Food And Beverage",
                "sector" => "Ice Creams & Yogurt Parlors",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Sabhyata",
                "logo" => "/topfranchiseleaders/staticLogo/2025/sabhyata.jpg",
                "industry" => "Retail",
                "sector" => "Women's Clothing",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Saravana Bhavan",
                "logo" => "/topfranchiseleaders/staticLogo/2025/saravanabhavan.jpg",
                "industry" => "Food And Beverage",
                "sector" => "Quick Service Restaurants",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Shallby Hospitals",
                "logo" => "/topfranchiseleaders/staticLogo/2025/shallbyhospitals.jpg",
                "industry" => "Beauty & Health",
                "sector" => "Hospitals",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "Swiggy Instamart",
                "logo" => "/topfranchiseleaders/staticLogo/2025/swiggyinstamart.jpg",
                "industry" => "Retail",
                "sector" => "E-Commerce & Related",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "The Pilates Studio",
                "logo" => "/topfranchiseleaders/staticLogo/2025/thepilatesstudio.jpg",
                "industry" => "Retail",
                "sector" => "Gyms And Fitness Centres",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "Aurelia",
                "logo" => "/topfranchiseleaders/staticLogo/2025/aurelia.jpg",
                "industry" => "Fashion",
                "sector" => "Womens Wear",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "Bhaichung Bhutia",
                "logo" => "/topfranchiseleaders/staticLogo/2025/bhaichungbhutia.jpg",
                "industry" => "Sports, Fitness & Entertainment",
                "sector" => "Sports & Gaming",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "Bonjour",
                "logo" => "/topfranchiseleaders/staticLogo/2025/bonjour.jpg",
                "industry" => "Fashion",
                "sector" => "Others Clothing",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "Bodycraft Salon",
                "logo" => "/topfranchiseleaders/staticLogo/2025/bodycraftsalon.jpg",
                "industry" => "Beauty & Health",
                "sector" => "Beauty Salons/ Unisex Salons/ Spa",
                "investment" => "Rs. 2 Cr - 5 Cr",
            ],
            [
                "brand" => "Oliva Skin and Hair Clinics",
                "logo" => "/topfranchiseleaders/staticLogo/2025/olivaskinandhairclinics.jpg",
                "industry" => "Beauty & Health",
                "sector" => "Clinics & Nursing Homes",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "Pigeon by Stovekraft",
                "logo" => "/topfranchiseleaders/staticLogo/2025/pigeonbystovekraft.jpg",
                "industry" => "Retail",
                "sector" => "Kitchen",
                "investment" => "Rs. 20 Lakh - 30 Lakh",
            ],
            [
                "brand" => "Portico",
                "logo" => "/topfranchiseleaders/staticLogo/2025/portico.jpg",
                "industry" => "Retail",
                "sector" => "Furniture/Home Decor & Furnishing",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "PVR INOX",
                "logo" => "/topfranchiseleaders/staticLogo/2025/pvrinox.jpg",
                "industry" => "Sports, Fitness & Entertainment",
                "sector" => "Movies (Multiplex)",
                "investment" => "Rs. 2 Cr - 5 Cr",
            ],
            [
                "brand" => "Soliatrio",
                "logo" => "/topfranchiseleaders/staticLogo/2025/soliatrio.jpg",
                "industry" => "Fashion",
                "sector" => "Precious Jewellery",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "The Ofen Bakery",
                "logo" => "/topfranchiseleaders/staticLogo/2025/theofenbakery.jpg",
                "industry" => "Food And Beverage",
                "sector" => "Bakery & Confectionary",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Adidas",
                "logo" => "/topfranchiseleaders/staticLogo/2025/adidas.jpg",
                "industry" => "Fashion",
                "sector" => "Sports",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Domino's",
                "logo" => "/topfranchiseleaders/staticLogo/2025/dominos.jpg",
                "industry" => "Food And Beverage",
                "sector" => "Pizzeria",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "Hyatt",
                "logo" => "/topfranchiseleaders/staticLogo/2025/hyatt.jpg",
                "industry" => "Hotel, Travel & Tourism",
                "sector" => "Hotel Chain",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "Marriott",
                "logo" => "/topfranchiseleaders/staticLogo/2025/marriott.jpg",
                "industry" => "Hotel, Travel & Tourism",
                "sector" => "Hotel Chain",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "Nike",
                "logo" => "/topfranchiseleaders/staticLogo/2025/nike.jpg",
                "industry" => "Fashion",
                "sector" => "Sports",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "Reebok",
                "logo" => "/topfranchiseleaders/staticLogo/2025/reebok.jpg",
                "industry" => "Fashion",
                "sector" => "Sports",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "Wyndham",
                "logo" => "/topfranchiseleaders/staticLogo/2025/wyndham.jpg",
                "industry" => "Hotel, Travel & Tourism",
                "sector" => "Hotel Chain",
                "investment" => "Rs. 5 Cr above",
            ],
        ],
        '2024' => [

            [
                "brand" => "Kotak Securities",
                "logo" => "/topfranchiseleaders/staticLogo/2024/kotaksecurities.webp",
                "industry" => "Business Services",
                "sector" => "Financial Investment & Trading",
                "investment" => "Rs. 50 K - 2 Lakh",
            ],
            [
                "brand" => "US POLO",
                "logo" => "/topfranchiseleaders/staticLogo/2024/uspolo.webp",
                "industry" => "Retail",
                "sector" => "Men's Footwear",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "W by TCNS",
                "logo" => "/topfranchiseleaders/staticLogo/2024/wbytcns.webp",
                "industry" => "Retail",
                "sector" => "Women's Clothing",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Caratlane",
                "logo" => "/topfranchiseleaders/staticLogo/2024/caratlane.webp",
                "industry" => "Retail",
                "sector" => "Designer Jewellery",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "Cultfit",
                "logo" => "/topfranchiseleaders/staticLogo/2024/cultfit.webp",
                "industry" => "Beauty & Health",
                "sector" => "Beauty Salons/ Unisex Salons/ Spa",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "Lemon Tree",
                "logo" => "/topfranchiseleaders/staticLogo/2024/lemontree.webp",
                "industry" => "Hotel, Travel & Tourism",
                "sector" => "Hotel Chain",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "Crossword",
                "logo" => "/topfranchiseleaders/staticLogo/2024/crossword.webp",
                "industry" => "Retail",
                "sector" => "Book Stores",
                "investment" => "Rs. 20 Lakh - 30 Lakh",
            ],
            [
                "brand" => "Ather",
                "logo" => "/topfranchiseleaders/staticLogo/2024/ather.webp",
                "industry" => "Automotive",
                "sector" => "Electric Vehicles Two Wheelers (EV)",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "Go Colors",
                "logo" => "/topfranchiseleaders/staticLogo/2024/gocolors.webp",
                "industry" => "Fashion",
                "sector" => "Readymade",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Heads up For Tails",
                "logo" => "/topfranchiseleaders/staticLogo/2024/headsupfortails.webp",
                "industry" => "Retail",
                "sector" => "Pet Stores",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "Mothers Pride",
                "logo" => "/topfranchiseleaders/staticLogo/2024/motherspride.webp",
                "industry" => "Education",
                "sector" => "Preschools",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "Prakruthi",
                "logo" => "/topfranchiseleaders/staticLogo/2024/prakruthi.webp",
                "industry" => "Education",
                "sector" => "School Tutoring",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "Hippo Stores",
                "logo" => "/topfranchiseleaders/staticLogo/2024/hippostores.webp",
                "industry" => "Retail",
                "sector" => "Department & Convenience Stores",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],

            [
                "brand" => "Domino's Pizza",
                "logo" => "/topfranchiseleaders/staticLogo/2024/dominos.webp",
                "industry" => "Food & Beverage",
                "sector" => "Quick Service Restaurants",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "Reebok",
                "logo" => "/topfranchiseleaders/staticLogo/2024/reebok.webp",
                "industry" => "Retail",
                "sector" => "Men's Footwear",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "Elle Décor Kitchens",
                "logo" => "/topfranchiseleaders/staticLogo/2024/elledecorkitchens.webp",
                "industry" => "Retail",
                "sector" => "Kitchen",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Marriott International",
                "logo" => "/topfranchiseleaders/staticLogo/2024/marriott.webp",
                "industry" => "Hotel, Travel & Tourism",
                "sector" => "Hotel Chain",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "Hyatt",
                "logo" => "/topfranchiseleaders/staticLogo/2024/hyatt.webp",
                "industry" => "Hotel, Travel & Tourism",
                "sector" => "Hotel Chain",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "Wyndhamm Hotel & Resorts",
                "logo" => "/topfranchiseleaders/staticLogo/2024/wyndham.webp",
                "industry" => "Hotel, Travel & Tourism",
                "sector" => "Hotel Chain",
                "investment" => "Rs. 5 Cr above",
            ],
        ],
        '2023' => [
            [
                "brand" => "AND",
                "logo" => "/topfranchiseleaders/staticLogo/2023/and.webp",
                "industry" => "Fashion",
                "sector" => "Womens Wear",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Kotak Securities",
                "logo" => "/topfranchiseleaders/staticLogo/2023/kotak.webp",
                "industry" => "Business Services",
                "sector" => "Financial Investment & Trading",
                "investment" => "Rs. 50 K - 2 Lakh",
            ],
            [
                "brand" => "Bhaichung Bhutia Football Schools",
                "logo" => "/topfranchiseleaders/staticLogo/2023/bhaichungbhutia.webp",
                "industry" => "Sports, Fitness & Entertainment",
                "sector" => "Sports & Gaming",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "Caratlane",
                "logo" => "/topfranchiseleaders/staticLogo/2023/caratlane.webp",
                "industry" => "Retail",
                "sector" => "Designer Jewellery",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "Hero Electric",
                "logo" => "/topfranchiseleaders/staticLogo/2023/heroelectric.webp",
                "industry" => "Automotive",
                "sector" => "Electric Vehicles Two Wheelers (EV)",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Joyalukkas",
                "logo" => "/topfranchiseleaders/staticLogo/2023/joyalukkas.webp",
                "industry" => "Retail",
                "sector" => "Designer Jewellery",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "Loom Solar",
                "logo" => "/topfranchiseleaders/staticLogo/2023/loomsolar.webp",
                "industry" => "Dealers & Distributors",
                "sector" => "Solar Products",
                "investment" => "Rs. 2 Lakh - 5 Lakh",
            ],
            [
                "brand" => "US POLO",
                "logo" => "/topfranchiseleaders/staticLogo/2023/uspolo.webp",
                "industry" => "Fashion",
                "sector" => "Readymade",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "W by TCNS",
                "logo" => "/topfranchiseleaders/staticLogo/2023/wbytcns.webp",
                "industry" => "Fashion",
                "sector" => "Womens Wear",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Babai Hotels",
                "logo" => "/topfranchiseleaders/staticLogo/2023/babaihotels.webp",
                "industry" => "Food & Beverage",
                "sector" => "Quick Service Restaurants",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "Heads up For Tails",
                "logo" => "/topfranchiseleaders/staticLogo/2023/headsupfortails.webp",
                "industry" => "Retail",
                "sector" => "Pet Stores",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "Innov8",
                "logo" => "/topfranchiseleaders/staticLogo/2023/innov8.webp",
                "industry" => "Business Services",
                "sector" => "Real Estate Sub",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "Mahesh Bhupathi Tennis Academy",
                "logo" => "/topfranchiseleaders/staticLogo/2023/maheshbhupathitennisacademy.webp",
                "industry" => "Sports, Fitness & Entertainment",
                "sector" => "Sports & Gaming",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Mystery Rooms",
                "logo" => "/topfranchiseleaders/staticLogo/2023/mysteryrooms.webp",
                "industry" => "Sports, Fitness & Entertainment",
                "sector" => "Sports & Gaming",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Dale Carnegie",
                "logo" => "/topfranchiseleaders/staticLogo/2023/dalecarnegie.webp",
                "industry" => "Education",
                "sector" => "Corporate Training",
                "investment" => "Rs. 5 Lakh - 10 Lakh",
            ],
            [
                "brand" => "Adidas",
                "logo" => "/topfranchiseleaders/staticLogo/2023/adidas.webp",
                "industry" => "Fashion",
                "sector" => "Sports",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Domino's Pizza",
                "logo" => "/topfranchiseleaders/staticLogo/2023/domino's.webp",
                "industry" => "Food & Beverage",
                "sector" => "Pizzeria",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "Hyatt",
                "logo" => "/topfranchiseleaders/staticLogo/2023/hyatt.webp",
                "industry" => "Hotel Travel & Tourism",
                "sector" => "Hotel Chain",
                "investment" => "Rs. 5 Cr above",
            ],
        ],
        '2022' => [
            [
                "brand" => "Hero Electric",
                "logo" => "/topfranchiseleaders/staticLogo/2022/heroelectric.webp",
                "industry" => "Automotive",
                "sector" => "Electric Vehicles Two Wheelers (EV)",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Hyatt",
                "logo" => "/topfranchiseleaders/staticLogo/2022/hyatt.webp",
                "industry" => "Hotel, Travel & Tourism",
                "sector" => "Hotel Chain",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "Nike",
                "logo" => "/topfranchiseleaders/staticLogo/2022/nike.webp",
                "industry" => "Retail",
                "sector" => "Men's Footwear",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "Pepe Jeans",
                "logo" => "/topfranchiseleaders/staticLogo/2022/pepejeans.webp",
                "industry" => "Fashion",
                "sector" => "Readymade",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "UNITED COLORS OF BENETTON",
                "logo" => "/topfranchiseleaders/staticLogo/2022/united.webp",
                "industry" => "Fashion",
                "sector" => "Readymade",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "CALVIN KLEIN",
                "logo" => "/topfranchiseleaders/staticLogo/2022/calvinklein.webp",
                "industry" => "Fashion",
                "sector" => "Readymade",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "KOTAK SECURITIES",
                "logo" => "/topfranchiseleaders/staticLogo/2022/kotak.webp",
                "industry" => "Business Services",
                "sector" => "Finance Advisors & Brokers",
                "investment" => "Rs. 2 Lakh - 5 Lakh",
            ],
            [
                "brand" => "WYNDHAM HOTELS",
                "logo" => "/topfranchiseleaders/staticLogo/2022/wyndham.webp",
                "industry" => "Hotel, Travel & Tourism",
                "sector" => "Hotel Chain",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "MARINO",
                "logo" => "/topfranchiseleaders/staticLogo/2022/marino.webp",
                "industry" => "Food And Beverage",
                "sector" => "Bakery & Confectionary",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "PIONEER FURNITURE",
                "logo" => "/topfranchiseleaders/staticLogo/2022/pioneer.webp",
                "industry" => "Retail",
                "sector" => "Furniture/Home Decor & Furnishing",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "DOMINOS",
                "logo" => "/topfranchiseleaders/staticLogo/2022/dominos.webp",
                "industry" => "Food And Beverage",
                "sector" => "Quick Service Restaurants",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "KFC",
                "logo" => "/topfranchiseleaders/staticLogo/2022/kfc.webp",
                "industry" => "Food And Beverage",
                "sector" => "Quick Service Restaurants",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "PIZZA HUT",
                "logo" => "/topfranchiseleaders/staticLogo/2022/pizzahut.webp",
                "industry" => "Food And Beverage",
                "sector" => "Pizzeria",
                "investment" => "Rs. 20 Lakh - 30 Lakh",
            ],
            [
                "brand" => "UNDER ARMOUR",
                "logo" => "/topfranchiseleaders/staticLogo/2022/underarmour.webp",
                "industry" => "Fashion",
                "sector" => "Sports Wear",
                "investment" => "Rs. 2 Cr - 5 Cr",
            ],
            [
                "brand" => "BARRY'S",
                "logo" => "/topfranchiseleaders/staticLogo/2022/barrys.webp",
                "industry" => "Beauty & Health",
                "sector" => "Gyms And Fitness Centres",
                "investment" => "Rs. 2 Cr - 5 Cr",
            ],
            [
                "brand" => "LAY BARE",
                "logo" => "/topfranchiseleaders/staticLogo/2022/laybare.webp",
                "industry" => "Beauty & Health",
                "sector" => "Cosmetic Accessories",
                "investment" => "Rs. 20 Lakh - 30 Lakh",
            ],
            [
                "brand" => "O'TACOS",
                "logo" => "/topfranchiseleaders/staticLogo/2022/otacos.webp",
                "industry" => "Food And Beverage",
                "sector" => "Quick Service Restaurants",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
        ],
        '2021' => [
            [
                "brand" => "Dominos",
                "logo" => "/topfranchiseleaders/staticLogo/2021/dominos.webp",
                "industry" => "Food And Beverage",
                "sector" => "Quick Service Restaurants",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "Hatsun Agro Products",
                "logo" => "/topfranchiseleaders/staticLogo/2021/hatsun.webp",
                "industry" => "Dealers & Distributors",
                "sector" => "Agro Products & Commodities",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "Hero Electric",
                "logo" => "/topfranchiseleaders/staticLogo/2021/heroelectric.webp",
                "industry" => "Automotive",
                "sector" => "Electric Vehicles Two Wheelers (EV)",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Hyatt",
                "logo" => "/topfranchiseleaders/staticLogo/2021/hyatt.webp",
                "industry" => "Hotel, Travel & Tourism",
                "sector" => "Hotel Chain",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "KFC",
                "logo" => "/topfranchiseleaders/staticLogo/2021/kfc.webp",
                "industry" => "Food And Beverage",
                "sector" => "Quick Service Restaurants",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "Lenovo",
                "logo" => "/topfranchiseleaders/staticLogo/2021/lenovo.webp",
                "industry" => "Dealers & Distributors",
                "sector" => "Consumer Electronics",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "Marriott",
                "logo" => "/topfranchiseleaders/staticLogo/2021/marriott.webp",
                "industry" => "Hotel Travel & Tourism",
                "sector" => "Hotel Chain",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "Samsung Smart Cafe/ Plaza",
                "logo" => "/topfranchiseleaders/staticLogo/2021/samsung.webp",
                "industry" => "Retail",
                "sector" => "Consumer Electronics",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "Wyndham hotels",
                "logo" => "/topfranchiseleaders/staticLogo/2021/wyndham.webp",
                "industry" => "Hotel, Travel & Tourism",
                "sector" => "Hotel Chain",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "Xiaomi",
                "logo" => "/topfranchiseleaders/staticLogo/2021/xiaomi.webp",
                "industry" => "Dealers & Distributors",
                "sector" => "Electronic Products & Components",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "Caratlane",
                "logo" => "/topfranchiseleaders/staticLogo/2021/caratlane.webp",
                "industry" => "Retail",
                "sector" => "Precious Jewellery",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "Cartrade",
                "logo" => "/topfranchiseleaders/staticLogo/2021/cartrade.webp",
                "industry" => "Automobile",
                "sector" => "Car Reselling",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "D’décor",
                "logo" => "/topfranchiseleaders/staticLogo/2021/decor.webp",
                "industry" => "Retail",
                "sector" => "Furniture/Home Decor & Furnishing",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "MFC services",
                "logo" => "/topfranchiseleaders/staticLogo/2021/mfc.webp",
                "industry" => "Business Services",
                "sector" => "Financial Investment & Trading",
                "investment" => "Rs. 2 Lakh - 5 Lakh",
            ],
            [
                "brand" => "Millenium education",
                "logo" => "/topfranchiseleaders/staticLogo/2021/millenium.webp",
                "industry" => "Education",
                "sector" => "Schools",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "Nike",
                "logo" => "/topfranchiseleaders/staticLogo/2021/nike.webp",
                "industry" => "Retail",
                "sector" => "Men's Footwear",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "Nobilla Kitchens",
                "logo" => "/topfranchiseleaders/staticLogo/2021/nobilla.webp",
                "industry" => "Retail",
                "sector" => "Kitchen",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Bubble Recap Beverage",
                "logo" => "/topfranchiseleaders/staticLogo/2021/bubblerecap.webp",
                "industry" => "Food And Beverage",
                "sector" => "Quick Service Restaurants",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "Whitehat jr",
                "logo" => "/topfranchiseleaders/staticLogo/2021/whitehat.webp",
                "industry" => "Education",
                "sector" => "After School Activities",
                "investment" => "Rs. 2 Lakh - 5 Lakh",
            ],
            [
                "brand" => "Chilli Bean",
                "logo" => "/topfranchiseleaders/staticLogo/2021/chilli.webp",
                "industry" => "Fashion",
                "sector" => "Opticians/Eye Wear",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "Engage & Grow",
                "logo" => "/topfranchiseleaders/staticLogo/2021/engage.webp",
                "industry" => "Business Services",
                "sector" => "Business",
                "investment" => "Rs. 2 Lakh - 5 Lakh",
            ],
            [
                "brand" => "Forex",
                "logo" => "/topfranchiseleaders/staticLogo/2021/forex.webp",
                "industry" => "Business Services",
                "sector" => "",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "Hoop Mountain",
                "logo" => "/topfranchiseleaders/staticLogo/2021/hoop.webp",
                "industry" => "Sports & Gaming",
                "sector" => "Sports & Gaming",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "No H20",
                "logo" => "/topfranchiseleaders/staticLogo/2021/noh20.webp",
                "industry" => "Automobile",
                "sector" => "Car Wash / Ceramic Coating / Detailing",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
        ],
        '2020' => [
            [
                "brand" => "Edelweiss",
                "logo" => "/topfranchiseleaders/staticLogo/2020/edelweiss.webp",
                "industry" => "Business Service",
                "sector" => "Microfinance",
                "investment" => "Rs. 2 Lakh - 5 Lakh",
            ],
            [
                "brand" => "Hero Electric",
                "logo" => "/topfranchiseleaders/staticLogo/2020/heroelectric.webp",
                "industry" => "Automobile",
                "sector" => "Electric Vehicles Two Wheelers (EV)",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "ICICIdirect",
                "logo" => "/topfranchiseleaders/staticLogo/2020/icici.webp",
                "industry" => "Business Service",
                "sector" => "Financial Investment & Trading",
                "investment" => "Rs. 2 Lakh - 5 Lakh",
            ],
            [
                "brand" => "W",
                "logo" => "/topfranchiseleaders/staticLogo/2020/w.webp",
                "industry" => "Fashion",
                "sector" => "Women's clothing",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Xiaomi",
                "logo" => "/topfranchiseleaders/staticLogo/2020/xiaomi.webp",
                "industry" => "Dealers & Distributors",
                "sector" => "Electronic Products & Components",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "Farzi Café",
                "logo" => "/topfranchiseleaders/staticLogo/2020/farzicafe.webp",
                "industry" => "Food And Beverage",
                "sector" => "Quick Service Restaurants",
                "investment" => "Rs. 2 Cr - 5 Cr",
            ],
            [
                "brand" => "Truelift & Hill",
                "logo" => "/topfranchiseleaders/staticLogo/2020/truelift-hill.webp",
                "industry" => "Beauty & Health",
                "sector" => "Cosmetic Accessories",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "BonBeno The Pawsome Store",
                "logo" => "/topfranchiseleaders/staticLogo/2020/bonbeno.webp",
                "industry" => "Retail",
                "sector" => "Pet Stores",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "Burger Revolution",
                "logo" => "/topfranchiseleaders/staticLogo/2020/burger-revolution.webp",
                "industry" => "Food And Beverage",
                "sector" => "Quick Service Restaurants",
                "investment" => "Rs. 5 Lakh - 10 Lakh",
            ],
            [
                "brand" => "Drivezy",
                "logo" => "/topfranchiseleaders/staticLogo/2020/drivezy.webp",
                "industry" => "Automobile",
                "sector" => "Car Rental",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Zomato",
                "logo" => "/topfranchiseleaders/staticLogo/2020/zomato.webp",
                "industry" => "Food And Beverage",
                "sector" => "Online Food Ordering Services",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Engage & Grow",
                "logo" => "/topfranchiseleaders/staticLogo/2020/engage-grow.webp",
                "industry" => "Business Service",
                "sector" => "Business",
                "investment" => "Rs. 2 Lakh - 5 Lakh",
            ],
            [
                "brand" => "Haagen Dazs",
                "logo" => "/topfranchiseleaders/staticLogo/2020/haagendazs.webp",
                "industry" => "Food And Beverage",
                "sector" => "Ice Creams & Yogurt Parlors",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "Ice Cream Lab",
                "logo" => "/topfranchiseleaders/staticLogo/2020/icecream-lab.webp",
                "industry" => "Food And Beverage",
                "sector" => "Ice Creams & Yogurt Parlors",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "Joost juice",
                "logo" => "/topfranchiseleaders/staticLogo/2020/joost.webp",
                "industry" => "Food And Beverage",
                "sector" => "Juices / Smoothies / Dairy Parlors",
                "investment" => "Rs. 20 Lakh - 30 Lakh",
            ],
            [
                "brand" => "Little Caesars",
                "logo" => "/topfranchiseleaders/staticLogo/2020/little-caesars.webp",
                "industry" => "Food And Beverage",
                "sector" => "Pizzeria",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "Little Kickers",
                "logo" => "/topfranchiseleaders/staticLogo/2020/little-kickers.webp",
                "industry" => "Sports, Fitness & Entertainment",
                "sector" => "Sports & Gaming",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "Logischool",
                "logo" => "/topfranchiseleaders/staticLogo/2020/logischool.webp",
                "industry" => "Education",
                "sector" => "Robotics & Technical Training/ AI",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "New Horizons",
                "logo" => "/topfranchiseleaders/staticLogo/2020/new-horizons.webp",
                "industry" => "Education",
                "sector" => "Degree/Diploma Colleges",
                "investment" => "Rs. 2 Cr - 5 Cr",
            ],
            [
                "brand" => "Sani Service",
                "logo" => "/topfranchiseleaders/staticLogo/2020/sani-service.webp",
                "industry" => "Business Service",
                "sector" => "Pollution Monitoring",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "Sbarro pizza",
                "logo" => "/topfranchiseleaders/staticLogo/2020/sbarro-pizza.webp",
                "industry" => "Food And Beverage",
                "sector" => "Quick Service Restaurants",
                "investment" => "Rs. 5 Cr above",
            ],
        ],
        '2019' => [
            [
                "brand" => "APOLLO TYRES",
                "logo" => "/topfranchiseleaders/staticLogo/2019/apollo-tyres.webp",
                "industry" => "Dealers & Distributors",
                "sector" => "Tyre, Tube, Accessories",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "EDELWEISS",
                "logo" => "/topfranchiseleaders/staticLogo/2019/edelweiss.webp",
                "industry" => "Business Service",
                "sector" => "Microfinance",
                "investment" => "Rs. 2 Lakh - 5 Lakh",
            ],
            [
                "brand" => "INDIA POST",
                "logo" => "/topfranchiseleaders/staticLogo/2019/india-post.webp",
                "industry" => "Business Services",
                "sector" => "Courier & Delivery",
                "investment" => "Rs. 5 Lakh - 10 Lakh",
            ],
            [
                "brand" => "KFC",
                "logo" => "/topfranchiseleaders/staticLogo/2019/kfc.webp",
                "industry" => "Food And Beverage",
                "sector" => "Casual Dine Restaurants",
                "investment" => "Rs. 1 Cr - 2 Cr",
            ],
            [
                "brand" => "KURL-ON",
                "logo" => "/topfranchiseleaders/staticLogo/2019/kurlon.webp",
                "industry" => "Dealers & Distributors",
                "sector" => "Home Furnishing",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "LOOKS SALON",
                "logo" => "/topfranchiseleaders/staticLogo/2019/looks-salon.webp",
                "industry" => "Beauty & Health",
                "sector" => "Beauty Salons",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "MARRIOTT",
                "logo" => "/topfranchiseleaders/staticLogo/2019/marriott.webp",
                "industry" => "Hotel Travel & Tourism",
                "sector" => "Hotel Chain",
                "investment" => "Rs. 5 Cr above",
            ],
            [
                "brand" => "MAX FASHIONS",
                "logo" => "/topfranchiseleaders/staticLogo/2019/max-fashions.webp",
                "industry" => "Retail",
                "sector" => "Readymade",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "Samsung Smart Café",
                "logo" => "/topfranchiseleaders/staticLogo/2019/samsung-smart-cafe.webp",
                "industry" => "Retail",
                "sector" => "Mobile & Communication/Internet Connections",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "SHAHNAZ HUSAIN",
                "logo" => "/topfranchiseleaders/staticLogo/2019/shahnaz-husain.webp",
                "industry" => "Beauty & Health",
                "sector" => "Beauty Salons",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "TALKWALKAR'S",
                "logo" => "/topfranchiseleaders/staticLogo/2019/talkwalkars.webp",
                "industry" => "Beauty & Health",
                "sector" => "Gyms And Fitness Centres",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "Sterling Holidays & Resorts",
                "logo" => "/topfranchiseleaders/staticLogo/2019/sterling-holidays.webp",
                "industry" => "Hotel Travel & Tourism",
                "sector" => "Hotel Chain",
                "investment" => "Rs. 2 Lakh - 5 Lakh",
            ],
            [
                "brand" => "HIMALAYA OPTICAL",
                "logo" => "/topfranchiseleaders/staticLogo/2019/himalaya-opticals.webp",
                "industry" => "Fashion",
                "sector" => "Opticians/Eye Wear",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "KRISPY KREME",
                "logo" => "/topfranchiseleaders/staticLogo/2019/krispy-kreme.webp",
                "industry" => "Food And Beverage",
                "sector" => "Quick Service Restaurants",
                "investment" => "Rs. 50 Lakh - 1 Cr",
            ],
            [
                "brand" => "TCNS CLOTHING",
                "logo" => "/topfranchiseleaders/staticLogo/2019/tcns-clothing.webp",
                "industry" => "Fashion",
                "sector" => "Womens Wear",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
            [
                "brand" => "XIAOMI",
                "logo" => "/topfranchiseleaders/staticLogo/2019/xiaomi.webp",
                "industry" => "Dealers & Distributors",
                "sector" => "Electronic Products & Components",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "BONBENO",
                "logo" => "/topfranchiseleaders/staticLogo/2019/bonbeno.webp",
                "industry" => "Retail",
                "sector" => "PET STORES",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "PHONEUP",
                "logo" => "/topfranchiseleaders/staticLogo/2019/phoneup.webp",
                "industry" => "Retail",
                "sector" => "Mobile & Communication/Internet Connections",
                "investment" => "INR 5 Lakh - 10 Lakh",
            ],
            [
                "brand" => "CUBE ELEVATORS",
                "logo" => "/topfranchiseleaders/staticLogo/2019/cube-elevators.webp",
                "industry" => "Dealers & Distributors",
                "sector" => "Cranes & Forklifts",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "DHADHOOM",
                "logo" => "/topfranchiseleaders/staticLogo/2019/dhadhoom.webp",
                "industry" => "Food And Beverage",
                "sector" => "Quick Service Restaurants",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "FARZI CAFÉ",
                "logo" => "/topfranchiseleaders/staticLogo/2019/farzi-cafe.webp",
                "industry" => "Food And Beverage",
                "sector" => "Quick Service Restaurants",
                "investment" => "Rs. 2 Cr - 5 Cr",
            ],
            [
                "brand" => "MOBEL",
                "logo" => "/topfranchiseleaders/staticLogo/2019/mobel.webp",
                "industry" => "Retail",
                "sector" => "Furniture/Home Decor & Furnishing",
                "investment" => "Rs. 20 Lakh - 30 Lakh",
            ],
            [
                "brand" => "SPEROWZ PRE SCHOOL",
                "logo" => "/topfranchiseleaders/staticLogo/2019/sperowz.webp",
                "industry" => "Education",
                "sector" => "Preschools",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "SRI SRI TATTVA",
                "logo" => "/topfranchiseleaders/staticLogo/2019/shri.webp",
                "industry" => "Beauty & Health",
                "sector" => "Others Health Care & Fitness",
                "investment" => "Rs. 10 Lakh - 20 Lakh",
            ],
            [
                "brand" => "THAT ITALIAN PLACE & CAFÉ BANCHETTA",
                "logo" => "/topfranchiseleaders/staticLogo/2019/that-italian.webp",
                "industry" => "Food And Beverage",
                "sector" => "Quick Service Restaurants",
                "investment" => "Rs. 30 Lakh - 50 Lakh",
            ],
        ],

    ],
];
