<?php
/**
 * Created by PhpStorm.
 * User: gulshan
 * Date: 7/8/18
 * Time: 5:03 PM
 */

$CategoryArr = [
        1 => "Beauty & Health",
        2 => "Food and Beverage",
        3 => "Education",
        5 => "Dealers & Distributors",
        6 => "Business Services",
        7 => "Home Based Business",
        8 => "Automotive",
        9 => "Retail",
        10 => "Fashion",
        11 => "Sports, Fitness & Entertainment",
        263 => "Hotel,
          Travel & Tourism",
        573 => "Industrial Machinery & Manufacturing"
    ];

$statesIndia    = [
    'AP' => 'Andhra Pradesh',
    'AR' => 'Arunachal Pradesh',
    'AS' => 'Assam',
    'BR' => 'Bihar',
    'CG' => 'Chhattisgarh',
    'GA' => 'Goa',
    'GJ' => 'Gujarat',
    'HR' => 'Haryana',
    'HP' => 'Himachal Pradesh',
    'JK' => 'Jammu and Kashmir',
    'JH' => 'Jharkhand',
    'KA' => 'Karnataka',
    'KL' => 'Kerala',
    'MP' => 'Madhya Pradesh',
    'MH' => 'Maharashtra',
    'MN' => 'Manipur',
    'ML' => 'Meghalaya',
    'MZ' => 'Mizoram',
    'NL' => 'Nagaland',
    'OR' => 'Orissa',
    'PB' => 'Punjab',
    'RJ' => 'Rajasthan',
    'SK' => 'Sikkim',
    'TN' => 'Tamil Nadu',
    'TS' => 'Telangana',
    'TR' => 'Tripura',
    'UK' => 'Uttarakhand',
    'UP' => 'Uttar Pradesh',
    'WB' => 'West Bengal',
    'AN' => 'Andaman and Nicobar Islands',
    'CH' => 'Chandigarh',
    'DH' => 'Dadra and Nagar Haveli',
    'DD' => 'Daman and Diu',
    'DL' => 'Delhi',
    'LD' => 'Lakshadweep',
    'PY' => 'Pondicherry'
];

function getCampaignSource()
{
    return [
        'website' =>1,
        'facebook' =>2,
        'FBDIP' =>2,	
        'FBLENT' =>2,				
        'entconf1' =>2,		
        'entconf2' =>2,				
        'eimpl2022' =>2,
        'PBE2022' =>2,				
        'SBE2022' =>2,
        'hydfb2022' =>2,								
        'mfsfacebooklead' =>2,
        'frovisitorfacebooklead' =>2,			
        'estateleadfacebook' =>2,				
        'linkedin' =>3,
        'LIShan' =>3,		
        'hydga2022' =>4,
        'google' =>4,
        'alakclicks' =>4,	
        'search' =>4,	
        'alak' =>4,	
        'SEARCHCONFEntrepreneur' =>4,	
        'EntConfnew1' =>2,	
        'EntConfnew2' =>2,	
        'EntConfgif1' =>2,	
        'EntConfLG' =>2,	
        'entaw3' =>2,	
        'entaw2' =>2,	
        'entaw1' =>2,
        'entawLG' =>2,		
        'ep07' =>4,		
        'search7' =>4,			
        'CONF' =>4,			
        'CONFDISPLAY' =>4,	
        'DDSCONF' =>4,	
        'GDDA' =>4,		
        'GRMKT' =>4,
        'GSEARCH2' =>4,
        'GSEARCH' =>4,				
        'DISPLAYMIX' =>4,	
        'DISPLAYMIXED' =>4,			
        'DISPLAYMIXEDKAPPA' =>4,	
        'SEARCHCONF' =>4,	
        'SEARCHCONFCPA' =>4,	
        'AWARDSEARCH07' =>4,		
        'DDS07' =>4,																	
        'googlesearch' =>4,
        'googledisplay' =>4,				
        'twitter' =>5,
        'eitw2022' =>5,		
        'dotnet' =>6,
        'dotcom' =>7,
        'business insider' =>8,
        'delhishow' =>9,
        'eb' =>11,
        'economictimes' =>12,
        'emailer' =>13,
        'mailer' =>13,		
        'socialorganic' =>14,
        'linkedinpromocode' =>15,
        'banner' =>16,
        'popup' =>17,
        'ABPNews' =>19,
        'Timesnow' =>20,
        'TheHindu' =>21,
        'ManormalOnline' =>22,
        'AMNETNewsCluster' =>23,
        'HT' =>24,
        'LiveMint' =>25,
        'LiveHindustan' =>26,
        'GoogleDisplayNetwork ' =>27,
        'Whatsapp' =>28,
        'SMS' =>29,
        'dv360' =>30,
        'instagram' =>31,
    ];
}
