<?php
function getCampaignSource()
{
    return [
        'website' =>1,
        'facebook' =>2,
        'entconf1' =>2,		
        'entconf2' =>2,				
        'eimpl2022' =>2,
        'PBE2022' =>2,				
        'SBE2022' =>2,
        'hydfb2022' =>2,								
        'mfsfacebooklead' =>2,
        'frovisitorfacebooklead' =>2,			
        'estateleadfacebook' =>2,				
        'linkedin' =>3,
        'hydga2022' =>4,
        'google' =>4,
        'alakclicks' =>4,	
        'search' =>4,	
        'alak' =>4,	
        'SEARCHCONFEntrepreneur' =>4,	
        'EntConfnew1' =>2,	
        'EntConfnew2' =>2,	
        'EntConfgif1' =>2,	
        'EntConfLG' =>2,	
        'entaw3' =>2,	
        'entaw2' =>2,	
        'entaw1' =>2,
        'entawLG' =>2,		
        'ep07' =>4,		
        'search7' =>4,			
        'CONF' =>4,			
        'CONFDISPLAY' =>4,	
        'DDSCONF' =>4,	
        'GDDA' =>4,		
        'GRMKT' =>4,
        'GSEARCH2' =>4,
        'GSEARCH' =>4,				
        'DISPLAYMIX' =>4,	
        'DISPLAYMIXED' =>4,			
        'DISPLAYMIXEDKAPPA' =>4,	
        'SEARCHCONF' =>4,	
        'SEARCHCONFCPA' =>4,	
        'AWARDSEARCH07' =>4,		
        'DDS07' =>4,																	
        'googlesearch' =>4,
        'googledisplay' =>4,				
        'twitter' =>5,
        'eitw2022' =>5,		
        'dotnet' =>6,
        'dotcom' =>7,
        'FIBanner' =>8,
        'fibanner' =>8,		
        'delhishow' =>9,
        'eb' =>11,
        'economictimes' =>12,
        'emailer' =>13,
        'mailer' =>13,		
        'socialorganic' =>14,
        'linkedinpromocode' =>15,
        'banner' =>16,
        'popup' =>17,
        'ABPNews' =>19,
        'Timesnow' =>20,
        'TheHindu' =>21,
        'ManormalOnline' =>22,
        'AMNETNewsCluster' =>23,
        'HT' =>24,
        'LiveMint' =>25,
        'LiveHindustan' =>26,
        'GoogleDisplayNetwork ' =>27,
        'Whatsapp' =>28,
        'SMS' =>29,
        'dv360' =>30,
        'instagram' =>31,
        '10times' =>32,		
        'Zoom' =>33,
        'Googleother' =>34,
        'googleother' =>34,					
        'Banner1' =>35,	
        'banner1' =>35,								
    ];
}

function getLeadType(){
	return [
        'Become an Exhibitor' =>18,
        'Become an Exhibitor - Dotcom' =>18,
        'Visit the Expo - LP Paid' =>14,
        'Visit the Expo - Paid' =>14,
        'Visit the Expo - DOTCOM' =>14,
        'Visit the Expo - LP - Free' =>14,												
        'Visit the Expo - LP - Paid' =>14,
        'Visit the Expo - DOTNET' =>14,
        'Attend the Conference' =>16,
        'Attend the Conference - Dotcom' =>16,
        'Visit the show' =>14,
        'Attend the congress' =>14,	
        'Nominate for Awards LP' =>15,
        'Self nominate for the awards' =>15,						
        'Visit the Expo - Popup' =>14,
        'Visit the Expo - Paid Ticket' =>14,												
        'Visit the Expo - LP Registration' =>14,
        'Visit the Expo - LP DOTNET' =>14,
        'Visit the Expo - LP - New' =>14,
        'Visit the Expo - LP' =>14,
        'Visit the Expo' =>14,
        'Become an Exhibitor/Partner' =>18,		
        'Become a Sponsor/Partner' =>20,						
        'Become a Partner' =>18,
        'Book Your Seat' =>16,
        'Exhibit at the congress' =>18,			
        'IRC Book Your Seat FOS' =>25,
        'IRC Book Your Seat FOS LP' =>25,
        'visit the show' => 14,
        'visit the show For Award' => 14,
        'Nominate for Awards' => 15,
        'Speak at the congress ' => 17,
        'Exhibit at the expo' => 18,
        'Partner for the event' => 18,
        'Brochure Download' => 19,
        'Sponsor the event' => 20,
        'Pitch Room' => 21,
        'Visit The Show - Oil' => 35 //visitor oil
	];
}

function replaceChar($string)
{
    $string = preg_replace('/[^^a-zA-Z0-9#@&-+:_(),.!@"\/ ]/','',$string);
    $string = preg_replace('!\s+!', ' ', $string);
    return $string;
}
?>